### ISSUE TITLE
Octavo is not available on crates.io

### ISSUE THREAD

**Issue by yberreby** [hauleth/octavo#23]
The README.md reads:

``` toml
[dependencies]
octavo = "*"
```

However, octavo isn't on crates.io as of writing, so this doesn't work.
